services:
  server:
    image: app/server
    build: ./server
    depends_on:
      - db
    volumes:
      - ./server:/app
    ports:
      - 3000:3000

  db:
    image: postgres:16.2-alpine3.18
    restart: always
    shm_size: 128mb
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432